import React from 'react';
import { createRoot } from 'react-dom/client';
import { RouterProvider, createRouter } from '@tanstack/react-router';
import { Toaster } from 'sonner';
import { AppProviders } from './providers/app-providers';
import { ErrorBoundary } from './components/error-boundary';
import { initAppearance } from './features/settings/use-desktop-settings';
import { routeTree } from './routeTree.gen';
import './design/global.css';

// Apply the reader's local accent / font / scaling overrides before first
// render. The pre-paint script in index.html has already set the light/dark
// class, so the accent's theme-scoped rules resolve on the first paint.
initAppearance();

// The router. `routeTree` is generated by @tanstack/router-plugin from the files
// in ./routes on `npm start` / build.
const router = createRouter({ routeTree });

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}

const container = document.getElementById('root');
if (!container) throw new Error('#root not found');

createRoot(container).render(
  <React.StrictMode>
    <ErrorBoundary>
      <AppProviders>
        <RouterProvider router={router} />
        <Toaster position="bottom-right" theme="system" richColors />
      </AppProviders>
    </ErrorBoundary>
  </React.StrictMode>,
);
